remove normalization of likelihood on cl-test
SCECcode/pycsep pull request #117
Opened 2021-04-30 17:47 UTC by bayonato89

2021-05-04 17:29 UTC, wsavran requested changes

2021-05-04 17:29 UTC, wsavran commented on csep/core/poisson_evaluations.py
> +# def _poisson_likelihood_test(forecast_data, observed_data, num_simulations=1000, random_numbers=None,
i think this comment somehow made it to the commit on accident.

2021-05-04 17:29 UTC, wsavran commented on csep/core/poisson_evaluations.py
> +    use_observed_counts (bool): if true, will simulate catalogs using the observed events, if false will draw from poisson distribution
these lines should be indented

2021-05-21 16:38 UTC, bayonato89 commented on csep/core/poisson_evaluations.py
> +    use_observed_counts (bool): if true, will simulate catalogs using the observed events, if false will draw from poisson distribution
Indented, Bill.

2021-06-03 16:12 UTC, bayonato89 commented
The lines are properly idented now :)

2021-06-17 17:51 UTC, wsavran commented
fixes #78

2021-06-17 18:27 UTC, wsavran commented
the ci build/test failed because of some python tabs vs. spaces issue in the poisson_evaluations.py file. @bayonato89 i fetched the branch from your forked copied and i fixed the spacing issues in the commit. the build and tests run without error.

i believe the original implementation of this pull request didn't produce the correct normalization / conditioning for the cl test. i went through the `_poisson_likelihood_test(...)` function and greatly simplified the logic for choosing the number of events to simulate and whether we want to normalize the likelihoods. before i merge these changes, @bayonato89 @mjw98 and @khawajasim do you all mind reviewing the changes to make sure that we have the correct form implemented?

**desired behavior for normalizing and conditioning**
TEST NAME | normalize_likelihood | use_observed_counts |
| ---- | ---- | ---- | 
|M-test| True | True |
|S-test| True | True |
|CL-test| False | True |
|L-test| False | False |

**implementation from previous commit**
```python
# used for conditional-likelihood, magnitude, and spatial tests to normalize the rate-component of the forecasts.
if use_observed_counts:
    scale = n_obs / n_fore
    if normalize_likelihood:
        expected_forecast_count = numpy.sum(forecast_data)
        log_bin_expectations = numpy.log(forecast_data.ravel())
    else:    
        expected_forecast_count = int(n_obs)
        log_bin_expectations = numpy.log(forecast_data.ravel() * scale)
else:
    expected_forecast_count = numpy.sum(forecast_data)
    log_bin_expectations = numpy.log(forecast_data.ravel())

# ... code omitted ...

for idx in range(num_simulations):
    if use_observed_counts:
        if normalize_likelihood:
            num_events_to_simulate = int(n_obs)
        else:    
            num_events_to_simulate = expected_forecast_count
    else:
        num_events_to_simulate = int(numpy.random.poisson(expected_forecast_count))
```

the error appears to be in the `if normalize_likelihood` clause, because if we are normalizing the likelihood we want to scale the rates to the observed rates. additionally, the m-test and s-test are called with `normalize_likelihood=True` and l-test and cl-test are called with `normalize_likelihood=False`. i propose a fix to this along with some simplification of the logic below.

**simplified implementation**
```python
expected_forecast_count = numpy.sum(forecast_data)
log_bin_expectations = numpy.log(forecast_data.ravel())
# used for conditional-likelihood, magnitude, and spatial tests to normalize the rate-component of the forecasts
if use_observed_counts and normalize_likelihood:
    scale = n_obs / n_fore
    expected_forecast_count = int(n_obs)
    log_bin_expectations = numpy.log(forecast_data.ravel() * scale)

# ... code omitted ...

for idx in range(num_simulations):
    if use_observed_counts:
        num_events_to_simulate = int(n_obs)
    else:
        num_events_to_simulate = int(numpy.random.poisson(expected_forecast_count))
```

in this implementation, we scale the rates when normalizing the likelihood and simulating using the observed event counts, else the rates aren't scaled. we now either simulate using the number of observed events or numbers drawn from a poisson distribution. the simplified version matches our desired behavior.

2021-06-17 18:30 UTC, wsavran approved these changes

2021-07-12 18:25 UTC, merged

2021-07-12 18:25 UTC, wsavran commented
@bayonato89 im merging this into master. nice job on finding this issue!