Added NZ catalog reader
SCECcode/pycsep pull request #213
Opened 2023-03-12 10:52 UTC by KennyGraham1

# pyCSEP Pull Request Checklist

Please check out the [contributing guidelines](https://github.com/SCECcode/pycsep/blob/master/CONTRIBUTING.md) for some tips 
on making pull requests to pyCSEP. 

Fixes issue #(*please fill in or delete if not needed*).

## Type of change:

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (this pull request adds no new code)
- [ ] Unpublished science feature (This may require a science review)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-03-16 08:08 UTC, fabiolsilva requested changes
Hi Kenny, thanks for sending the revised pull request. I ran the tests and things seem to work fine. I went through the code today and had a discussion with Bill regarding a few of these changes. Please take a look at my comments, and let me know if you have any questions.

Thanks!

2023-03-28 07:02 UTC, KennyGraham1 commented on tests/test_gns.py
> +def test_search():
Hi, @fabiolsilva I've made the changes we discussed. Thanks

2023-03-28 16:25 UTC, KennyGraham1 commented
@fabiolsilva I've committed the new yaml file. Thanks

2023-05-02 16:28 UTC, fabiolsilva approved these changes

2023-05-02 16:30 UTC, merged