added gcmt accessor from ISC API.  Follows the same logic than comcat…
SCECcode/pycsep pull request #217
Opened 2023-04-11 14:03 UTC by pabloitu

Added gcmt accessor from ISC API.  Follows the same logic than comcat and bsi readers. Created test for an event search and summary info from a request.

# pyCSEP Pull Request Checklist

Please check out the [contributing guidelines](https://github.com/SCECcode/pycsep/blob/master/CONTRIBUTING.md) for some tips 
on making pull requests to pyCSEP. 

Fixes issue #(*please fill in or delete if not needed*).

## Type of change:

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-05-03 06:40 UTC, fabiolsilva requested changes

2023-05-03 06:40 UTC, fabiolsilva commented on csep/utils/readers.py
> +def _query_gcmt(out_format='QuakeML',
I think this is now conflicting with the just merged pull request for the GNS catalog. This function is exactly at the same place as query_gns, and is causing the conflict. Could you resolve the conflict using the updated version in the master branch? Once that is done, I'll take another look to confirm everything is good and then merge this into master for the upcoming release.

Let me know if you have any questions.

Thanks!!!

2023-05-05 06:51 UTC, fabiolsilva commented on csep/utils/readers.py
> +def _query_gcmt(out_format='QuakeML',
Thanks!

2023-05-05 06:51 UTC, fabiolsilva approved these changes

2023-05-16 20:17 UTC, pabloitu commented
reworked into reading gcmt from IRIS instead of ISC, which takes less time and gives less query issues.

2023-05-16 21:26 UTC, pabloitu commented
*note:  In the tests/build workflow, the conda environment build is taking too long https://github.com/SCECcode/pycsep/blob/c19ce9f1a7a898987c8697440098bc2f51bc9088/.github/workflows/build-test.yml#L32

and sometimes it gives up of building the environment and just fail the workflow. We maybe should build the environment differently.

2023-05-30 06:49 UTC, merged