Add utility functions: (1) plotting ROC curve and (2) function to calculate Kagan_I_1_score
SCECcode/pycsep pull request #98
Opened 2021-03-21 19:09 UTC by hanbao-ucla

2021-03-21 19:11 UTC, wsavran commented
right on! ill take a look at this in some more detail on monday. just so you know, you can keep posting commits to this pull request if you'd like to make changes. no need to close and re-open.

2021-03-21 19:16 UTC, hanbao-ucla commented
Oh! Didn't know that! Do I just make changed in my own branch? I mean the branch that I'm trying to push to the upstream master?

2021-03-21 19:18 UTC, wsavran commented
Yes, every commit that you make to the branch `csep-feat-han` will show up in this pull request. it will re-build and test to make sure that any new commits don't break the build. its a cool feature.

2021-03-21 19:21 UTC, hanbao-ucla commented
Sounds great. Thanks Bill! 
Btw, I've tested against the most up-to-date upstream master version and it works well.

2021-03-21 19:24 UTC, wsavran commented
great ill post in this thread as soon as i look over everything!

2021-03-21 19:24 UTC, hanbao-ucla commented
No rush, Bill! ;)

2021-04-26 14:53 UTC, wsavran commented
hi @hanbao-ucla, sorry its taken me so long to look at this, but im ready to start moving toward getting these new functions into pycsep. im going to put some code review notes in there. specifically, there are some utility functions that exist that should be used and we want to make the overall functionality of the plotting routines similiar. eg., in tthe other functions we accept multiple forecasts and a single testing catalog. im going to put some mroe notes into the code review.

2021-04-26 16:17 UTC, hanbao-ucla commented
Hi Bill,

No problem. Feel free to let me know if there is anything you need me to do. :)

2021-04-26 16:54 UTC, wsavran commented
i left a few comments in the code review. let me know what you think about them

2021-04-26 17:01 UTC, hanbao-ucla commented
Bill, I don't see your code review comment.

2021-04-26 17:06 UTC, wsavran requested changes

2021-04-26 17:06 UTC, wsavran commented
my apologies! it looks like i never push the final 'submit' button

2021-04-26 17:09 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    earth_radius_km = 6371.
Agree.

2021-04-26 17:11 UTC, hanbao-ucla commented on csep/utils/plots.py
> +            TESTED EVENT FALLS IN)
Got it!

2021-04-26 17:13 UTC, hanbao-ucla commented on csep/utils/plots.py
> +        area_km2[i] = strip_area_steradian * R2 / (360.0/d_lon)
Sounds great to me! If so, we will have the dimension array of 'Area' same as that of the 'Bin-lat' or 'Bin-lon'

2021-04-26 17:14 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    rate = forecast.spatial_counts() # get [rate per cell] for all cells
Thanks! Yeah you are right.

2021-04-26 17:15 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    I = np.argsort(rate)             # get index of descending sort
Oh, I see. Yeah... I was commenting the two lines (line 1498 & 1499) together. But you are right.

2021-04-26 17:19 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    for j,subcatalog in enumerate(catalogs):
Oh! Haha, this is just what I was doing. I was testing one forecast against different years and different magnitudes.... If this is abnormal, we can definitely change it.

2021-04-26 17:25 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    # outFile = 'ROC_comp_M5M7.png'
Thanks for picking that up!

2021-04-26 17:26 UTC, hanbao-ucla commented on csep/utils/plots.py
> +            evt_counts[idx] = evt_counts[idx] + 1
Thanks! Yeah it make sense to me.

2021-04-26 17:26 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    return fig, ax
Message well received!

2021-04-26 17:27 UTC, hanbao-ucla commented
Thanks Bill. You comments are right on.

2021-04-26 17:29 UTC, khawajasim commented on csep/utils/plots.py
> +        area_km2[i] = strip_area_steradian * R2 / (360.0/d_lon)
that would be great.

2021-06-17 20:25 UTC, wsavran commented
@hanbao-ucla i just merged a pull request that adds the area function into regions.py. you can just pull those changes into this pull request and use that area function.

2021-06-20 02:54 UTC, hanbao-ucla commented on csep/utils/plots.py
> +            TESTED EVENT FALLS IN)
fixed.

2021-06-20 02:56 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    earth_radius_km = 6371.
Added in csep/utils/constants

2021-06-20 02:58 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    rate = forecast.spatial_counts() # get [rate per cell] for all cells
Fixed

2021-06-20 02:59 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    I = np.argsort(rate)             # get index of descending sort
fixed.

2021-06-20 03:20 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    # outFile = 'ROC_comp_M5M7.png'
fixed.

2021-06-20 03:26 UTC, hanbao-ucla commented on csep/utils/plots.py
> +        area_km2[i] = strip_area_steradian * R2 / (360.0/d_lon)
fixed. Using the newly added function (by Bill Savran) core.regions.geographical_area_from_bounds(lon1,lat1,lon2,lat2)

2021-06-20 03:34 UTC, hanbao-ucla commented on csep/utils/stats.py
> +    earth_radius_km = 6371.
Fixed.

2021-06-20 03:44 UTC, hanbao-ucla commented on csep/utils/stats.py
> +    total_area = np.sum(area_km2) # Total Area
Fixed.  Using the newly added function (by Bill Savran) core.regions.geographical_area_from_bounds(lon1,lat1,lon2,lat2)

2021-06-20 07:25 UTC, hanbao-ucla commented on csep/utils/plots.py
> +            evt_counts[idx] = evt_counts[idx] + 1
Fixed. Just need to feed the forecast.region to the catalog to using catalog.spatial_counts().
The code is much more beautiful now than before :)

2021-06-20 07:26 UTC, hanbao-ucla commented on csep/utils/stats.py
> +        I_1[j] = sum(score)/N_event
Fixed. Now using function catalog.spatial_counts()

2021-06-20 08:03 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    for j,subcatalog in enumerate(catalogs):
Fixed. Now accepting single or multiple forecasts but only one catalog.

2021-06-20 08:16 UTC, hanbao-ucla commented on csep/utils/plots.py
> +    return fig, ax
Fixed the axes input/output problem as your suggestion.

I don't think the current ROC curve has any EvaluationResult (values for further evaluation).

2021-06-20 08:29 UTC, hanbao-ucla commented
Hi Bill,

I've addressed all of your comments, and I think it is now ready to be merged. :)

++Han

2021-06-20 14:43 UTC, wsavran commented
thats great @hanbao-ucla ! i'm running the automated build and test now. ill review the code and hopefully merge tomorrow!

2021-11-04 20:06 UTC, hanbao-ucla commented
All bugs fixed. Documentations updated. I think it can be merged now.

2021-11-05 19:55 UTC, wsavran commented
thanks for the updates @hanbao-ucla. now that the ci tools are fixed im going to checkout this pull request.

2021-11-16 16:26 UTC, merged